version: "3.4"

services:
  mariadb:
    image: mariadb:10.3
    ports:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
      - MYSQL_DATABASE=db
    labels:
      com.symfony.server.service-prefix: 'DATABASE'
